<?php
/**
 * Page Template
 * Template Name: Gallery
 * Please do not edit this file. This file is part of the Cyber Chimps Framework and all modifications
 * should be made in a child theme.
 *
 * @category CyberChimps Framework
 * @package  Framework
 * @since    1.0
 * @author   Jope
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v3.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

global $theme_object;

get_header();
?>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

<script type="text/javascript" src="<?php bloginfo('template_directory'); ?>/inc/lightcase/jquery.events.touch.js"></script>

<script type="text/javascript" src="<?php bloginfo('template_directory'); ?>/inc/lightcase/lightcase.js"></script>

<link rel="stylesheet" href="<?php bloginfo('template_directory'); ?>/inc/lightcase/lightcase.css" type="text/css" media="all" />

<link rel="stylesheet" href="style.css" type="text/css" media="all" />

<script type="text/javascript"> 
    jQuery(document).ready(function($) {
   // $('a[data-rel^=lightcase]').lightcase(); 
    $('a[data-rel="lightcase:group"]').lightcase({maxWidth : 3000, maxHeight : 2000});
}); 

</script>
<div class="container-full-width" id="page_section_section">
    <div class="container">
        <div class="container-fluid">
            <article class="page type-page status-publish hentry">
                <header class="entry-header"><h1 class="entry-title">Bildarkivet</h1></header>
                   <div class="entry-summary">
                       <div class="thumbs">
                       <a href="<?php bloginfo('template_directory'); ?>/images/events/rsa_14/1.jpg" title="Hear nothing, See nothing, Say nothing Hear nothing, See nothing, Say nothing Hear nothing, See nothing, Say nothing." data-rel="lightcase:group"><img src="<?php bloginfo('template_directory'); ?>/images/events/rsa_14/1.jpg" /></a>
                       <a href="<?php bloginfo('template_directory'); ?>/images/events/rsa_14/2.jpg" data-rel="lightcase:group"><img src="<?php bloginfo('template_directory'); ?>/images/events/rsa_14/2.jpg" /></a>
                       <a href="<?php bloginfo('template_directory'); ?>/images/events/rsa_14/3.jpg" data-rel="lightcase:group"><img src="<?php bloginfo('template_directory'); ?>/images/events/rsa_14/3.jpg" /></a>
                       <a href="<?php bloginfo('template_directory'); ?>/images/events/rsa_14/4.jpg" title="Hear nothing, See nothing, Say nothing Hear nothing, See nothing, Say nothing Hear nothing, See nothing, Say nothing." data-rel="lightcase:group"><img src="<?php bloginfo('template_directory'); ?>/images/events/rsa_14/4.jpg" /></a>
                       <a href="<?php bloginfo('template_directory'); ?>/images/events/rsa_14/5.jpg" data-rel="lightcase:group"><img src="<?php bloginfo('template_directory'); ?>/images/events/rsa_14/5.jpg" /></a>
                       <a href="<?php bloginfo('template_directory'); ?>/images/events/rsa_14/6.jpg" data-rel="lightcase:group"><img src="<?php bloginfo('template_directory'); ?>/images/events/rsa_14/6.jpg" /></a>
                       <a href="<?php bloginfo('template_directory'); ?>/images/events/rsa_14/7.jpg" title="Hear nothing, See nothing, Say nothing Hear nothing, See nothing, Say nothing Hear nothing, See nothing, Say nothing." data-rel="lightcase:group"><img src="<?php bloginfo('template_directory'); ?>/images/events/rsa_14/7.jpg" /></a>
                       <a href="<?php bloginfo('template_directory'); ?>/images/events/rsa_14/8.jpg" data-rel="lightcase:group"><img src="<?php bloginfo('template_directory'); ?>/images/events/rsa_14/8.jpg"/></a>
                       <a href="<?php bloginfo('template_directory'); ?>/images/events/rsa_14/9.jpg" data-rel="lightcase:group"><img src="<?php bloginfo('template_directory'); ?>/images/events/rsa_14/9.jpg" /></a>
                       </div>
                </div>
            </article>
        </div>
    </div>
</div>
<?php get_footer();?>