<?php
/**
 * Page Template
 * Template Name: Clubhouse entren
 * Please do not edit this file. This file is part of the Cyber Chimps Framework and all modifications
 * should be made in a child theme.
 *
 * @category CyberChimps Framework
 * @package  Framework
 * @since    1.0
 * @author   Jope
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v3.0 (or later)
 * @link     http://www.cyberchimps.com/
 */
session_start();
if (isset($_SESSION['ch'])) {
    header( 'Location: klubbhuset' ) ;
}
global $wpdb;
$msg = '';
$entren = ' - entrén';

if (isset($_POST['email'])) {
   $email = $_POST['email']; 
   $send_cred = $wpdb->get_results( "SELECT losen, anvid
                                     FROM medlem
                                     WHERE epost = '$email'");
   if ($send_cred) {
       //$msg = 'Användarnamn > ' . $send_cred[0]->anvid . '<br />Lösenord > ' . $send_cred[0]->losen;
       $msg = '<p style="color:blue;">Inloggningsuppgifter har skickats till dig</p>';
   } else {
       $msg = '<p style="color:red;">Epostadressen hittades inte!<br />Försök igen...</p>';
   }
} 

if (isset($_POST['password'])) {
   $password = $_POST['password']; 
   $username = $_POST['username'];
   $login = $wpdb->get_results( "SELECT id, fornamn, efternamn
                                 FROM medlem
                                 WHERE anvid = '$username'
                                 AND losen = '$password'");
   if ($login) {
        $_SESSION['ch'] = array('id'=>$login[0]->id,'fname'=>$login[0]->fornamn,'lname'=>$login[0]->efternamn);
        header( 'Location: klubbhuset' ) ;
   } else {
       $nogo = '<p style="color:red;">Felaktig inloggning!</p>';
   }
}

global $theme_object;
get_header();
?>

<?php do_action('cyberchimps_before_container'); ?>

<div class="container-full-width" id="page_section_section">
    <div class="container">
        <div class="container-fluid">
            <div id="container" class="row-fluid">
                <div id="content" class=" span12">
                    <article class="page type-page status-publish hentry">
                        <header class="entry-header"><h1 class="entry-title">Klubbhuset<?php echo $entren; ?></h1>	</header>
                        <div class="entry-summary">
                        <?php if ($go) {
                                echo $go;
                            } else {?>
                        
                            
                            <div id="widget_boxes_container" class="row-fluid">
                                <div class="boxes">
                                    <div style="height: 350px; cursor: default;" class="box span4">
                                        <p><b>Logga in </b></p>                                          

                                        <img class="box-image" src="<?php echo get_template_directory_uri(); ?>/images/buttons/btn-login.png"/>
                                        <?php if($nogo) {
                                            echo $nogo;
                                        }
                                        ?>
                                        <p>
                                        <form method="post" action="">
                                            <input type="text" name="username" placeholder="Användarnamn"><br />
                                            <input type="password" name="password" placeholder="Lösenord"><br />
                                            <input type="submit" name="login" value="Logga in">
                                        </form>
                                        </p>
                                    </div>
                                    <!--end box1-->

                                    <div style="height: 350px; cursor: default;" class="box span4">
                                        <p><b>Glömt lösenord?</b></p> 

                                        <img class="box-image" src="<?php echo get_template_directory_uri(); ?>/images/buttons/btn-lostpw.png">
                                        <?php if($msg) {
                                            echo $msg;
                                        } else {
                                            echo '<p>Fyll i din epostadress så skickas inloggningsuppgifterna till dig</p>';
                                        }?>
                                        <p>
                                        <form method="post" action="">
                                            <input type="text" name="email" placeholder="Din epostadress"><br />

                                            <input type="submit" name="login" value="Skicka efter">
                                        </form>
                                        </p>
                                    </div>
                                    <!--end box2-->

                                    <div style="height: 350px; cursor: default;" class="box span4">
                                        <p><b>Inte medlem än?</b></p>
                                        <a href="http://singelgolf.besaba.com/start/medlemsanmalan/" class="box-link">
                                            <img class="box-image" src="<?php echo get_template_directory_uri(); ?>/images/buttons/btn-apply.png"></a>
                                        <p>Vad väntar du på?</p>
                                        <p>Anmäl dig här</p>
                                        <p><button>Medlemsanmälan</button></p>
                                    </div>
                                    <!--end box3-->
                                </div>
                                <!-- end boxes -->
                            </div>
                            <img src ="<?php echo get_template_directory_uri(); ?>/images/branding/slide1.jpg">
                            <?php }?>

                            
                        </div>
                    </article>    
                </div>
            </div>    
        </div>
    </div>
</div>

<?php do_action('cyberchimps_after_container'); ?>

<?php
get_footer();
function cyberchimps_page_display()
{
    
}
?>

