<?php
/**
 * Page Template
 * Template Name: Clubhouse
 * Please do not edit this file. This file is part of the Cyber Chimps Framework and all modifications
 * should be made in a child theme.
 *
 * @category CyberChimps Framework
 * @package  Framework
 * @since    1.0
 * @author   Jope
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v3.0 (or later)
 * @link     http://www.cyberchimps.com/
 */
session_start();
if (!isset($_SESSION['ch'])) {
    header('Location: klubbhusentren');
}

include_once('functions-jope.php');

if (isset($_GET['pa'])) {
    switch ($_GET['pa']) {
        case '1':
            $page = 'Resemeny & bokning';
            break;
        case '2':
            $page = 'Mina bokningar';
            break;
        case '3':
            $page = 'Mitt konto';
            break;
        case '4':
            $page = 'Mitt rum';
            break;
        case '5':
            session_destroy(); 
            header('Location: klubbhusentren');
            break;
        default:
            break;
    }
    $ch_breadcrumb = $_SESSION['ch']['fname'] . ' ' . $_SESSION['ch']['lname'] . ' / ' . $page;
} else {
    $ch_breadcrumb = 'Välkommen in ' . $_SESSION['ch']['fname'] . ' ' . $_SESSION['ch']['lname'];
}
global $theme_object;
get_header();
?>

<?php do_action('cyberchimps_before_container'); ?>
<div class="container-full-width" id="page_section_section">
    <div class="container">
        <div class="container-fluid">
            <div id="container" class="row-fluid">
                <div id="content" class=" span12">
                    <article class="page type-page status-publish hentry">
                        <header class="entry-header">
                            <h1 class="entry-title">Klubbhuset
                                <span class="entry-title-smaller"><?php echo $ch_breadcrumb; ?></span></h1>
                        </header>
                        <div class="entry-summary">
                            <div id="ch-menu">
                                <a class="b-menu" href="?pa=1">Resemeny & bokning</a>
                                <a class="b-menu" href="?pa=2">Mina bokningar</a>
                                <a class="b-menu" href="?pa=3">Mitt konto</a>
                                <a class="b-menu" href="?pa=4">Mitt rum</a>
                                <a class="l-menu" href="?pa=5">Logga ut</a>

                            </div><div class="clr"></div>
                            <div id="ch-content">
                                <?php
                                if (isset($_GET['pa'])) {
                                    switch ($_GET['pa']) {
                                        case '1':
                                            include 'page-booking.php';
                                            break;
                                        case '2':
                                            include 'page-mybookings.php';
                                            break;
                                        case '3':
                                            include 'page-account.php';
                                            break;
                                        case '4':
                                            include 'page-myroom.php';
                                            break;
                                        default:
                                            break;
                                    }
                                }
                                ?>
                            </div>   
                        </div>
                    </article>    
                </div>
            </div>    
        </div>
    </div>
</div>

<?php do_action('cyberchimps_after_container'); ?>

<?php
get_footer();
function cyberchimps_page_display()
{
    
}
?>
